blank_issues_enabled: false
contact_links:
  - name: Consul-K8s Community Support
    url: https://discuss.hashicorp.com/c/consul/29
    about: If you have a question, or are looking for advice, please post on our Discuss forum! The community loves to chime in to help. Happy Coding!
  - name: Consul-K8s GitHub Issues
    url: https://github.com/hashicorp/consul-k8s
    about: Are you submitting an issue or feature enhancement for the Consul-K8s binary? Please post in the Consul-K8s GitHub Issues.
  - name: Consul-K8s Learn Tracks
    url: https://learn.hashicorp.com/collections/consul/kubernetes
    about: Please check out our Learn Guides. These hands on guides deal with many of the tasks common to using Consul-K8s
