apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-slave2-consul
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: consul-storage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-slave2/pv-nfs-slave2-consul-1Gi
    server: 192.168.0.56