apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-slave1-consul
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-slave1/pv-nfs-slave1-consul-1Gi
    server: 192.168.0.55 